name: "binaries"

on: [push]

jobs:
  linux: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
 
    - name: Install dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install gzip -y
        sudo apt-get install xz-utils -y
        sudo apt-get install libreadline-dev -y

    - name: Show GCC
      run: gcc -v

    - name: Setup Lua
      run: |
        curl -O https://www.lua.org/ftp/lua-5.1.5.tar.gz
        tar -xzf lua-5.1.5.tar.gz
        cd lua-5.1.5
        make linux
        cd ..

    - name: Get LPeg
      run: |
        curl -L http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.0.2.tar.gz > lpeg.tar.gz
        tar -xzf lpeg.tar.gz

    - name: Get Luafilesystem
      run: |
        curl -L -o luafilesystem.tar.gz https://github.com/keplerproject/luafilesystem/archive/v1_8_0.tar.gz
        tar -xzf luafilesystem.tar.gz

    - name: Build
      run: gcc -Ilua-5.1.5/src/ -Llua-5.1.5/src/ bin/binaries/moon.c lpeg-1.0.2/lpvm.c lpeg-1.0.2/lpcap.c lpeg-1.0.2/lptree.c lpeg-1.0.2/lpcode.c lpeg-1.0.2/lpprint.c -l:liblua.a -lm -o moon-out


  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - uses: msys2/setup-msys2@v2
      with:
        install: gcc make curl

    - name: Show GCC
      run: gcc -v

    - name: Setup Lua
      run: |
        curl -O https://www.lua.org/ftp/lua-5.1.5.tar.gz
        tar -xZf lua-5.1.5.tar.gz
        cd lua-5.1.5
        make PLAT=mingw
        cd ..

    - name: Get LPeg
      run: |
        curl -L http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.0.2.tar.gz > lpeg.tar.gz
        tar -xZf lpeg.tar.gz

    - name: Get Luafilesystem
      run: |
        curl -L -o luafilesystem.tar.gz https://github.com/keplerproject/luafilesystem/archive/v1_8_0.tar.gz
        tar -xZf luafilesystem.tar.gz

    - name: List Files
      run: Get-ChildItem -Recurse

    - name: Run Lua
      run: "lua-5.1.5/src/lua.exe" -v

    - name: Build
      run: gcc -Ilua-5.1.5/src/ -Llua-5.1.5/src/ bin/binaries/moon.c lpeg-1.0.2/lpvm.c lpeg-1.0.2/lpcap.c lpeg-1.0.2/lptree.c lpeg-1.0.2/lpcode.c lpeg-1.0.2/lpprint.c -l:liblua.a -lm -o moon.exe




